// swift-tools-version: 6.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "yomikit",
    platforms: [
        .iOS(.v16),
        .macOS(.v13),
        .macCatalyst(.v16),
        .visionOS(.v1),
    ],
    products: [
        // Platform-independent layout analysis, table reconstruction,
        // receipt extraction and Japanese text post-processing.
        // Builds and tests on Linux.
        .library(name: "YomiKitCore", targets: ["YomiKitCore"]),
        // Apple platform layer: Vision / Core ML recognition wired into the
        // YomiKitCore pipeline. Compiles to an empty module on other platforms
        // (all sources are guarded by `#if canImport(Vision)` etc.).
        .library(name: "YomiKit", targets: ["YomiKit"]),
    ],
    targets: [
        .target(
            name: "YomiKitCore",
            swiftSettings: [
                .enableUpcomingFeature("ExistentialAny")
            ]
        ),
        .target(
            name: "YomiKit",
            dependencies: ["YomiKitCore"],
            swiftSettings: [
                .enableUpcomingFeature("ExistentialAny")
            ]
        ),
        .testTarget(
            name: "YomiKitCoreTests",
            dependencies: ["YomiKitCore"],
            resources: [
                // Contract fixtures generated by actually running
                // tools/distill_recognizer.py + tools/convert_recognizer.py
                // against a tiny randomly-initialized model (no weights are
                // committed; the fixtures are small JSON files).
                .copy("Resources")
            ]
        ),
        .testTarget(
            name: "YomiKitTests",
            dependencies: ["YomiKit", "YomiKitCore"]
        ),
    ]
)
